remote_theme: jekyll-theme-phantom
# Site settings
title: viflorenz
<a href='https://l8qmzv-victoria-florenzano.shinyapps.io/MonitorSocial_RiesgosSocAmbientales/'target="_blank" rel="noopener noreferrer">'Ejemplo'</a>
